name: Run Login Script

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"  # 每天 UTC 8:00 运行（北京时间 16:00）
  push:
    branches:
      - main

jobs:
  login:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 仓库代码
        uses: actions/checkout@v4  # 更新到最新版本

      - name: 设置 Python 环境
        uses: actions/setup-python@v5  # 更新到最新版本
        with:
          python-version: '3.13'  # 明确指定 Python 3.13，与之前日志一致

      - name: Create accounts.json from environment variable
        run: |
          echo "$ACCOUNTS_JSON" > accounts.json
          python -c "import json; json.load(open('accounts.json'))"  # 验证 JSON 格式
        env:
          ACCOUNTS_JSON: ${{ secrets.ACCOUNTS_JSON }}

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install pyppeteer aiofiles requests pytz  # 添加 pytz

      - name: 运行登录脚本
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          ACCOUNTS_JSON: ${{ secrets.ACCOUNTS_JSON }}
        run: |
          python login_script.py

  keepalive-workflow:
    name: Keepalive Workflow
    if: ${{ always() }}
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1
